import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit sidebar. Reading order, front to back:
 *
 *   Start Here
 *   Foundations          -- mechanism: what a model is doing
 *   Building Blocks       -- the pieces every agentic system assembles from
 *   Part 1 -- Patterns    -- the book: 8 design-decision chapters
 *   Part 2 -- Teardowns   -- the book: 4 real systems, read from source
 *   Reference: Infrastructure  -- entered from a Part 1 chapter, not read cold
 *   Reference: Production
 *   Reference: Frontier
 *   Glossary
 *
 * Two v1 pages are cross-listed into Building Blocks because they are
 * prerequisite tooling/UX for Part 1, not frontier or infrastructure
 * material: orchestration-frameworks (moved from Meta-Infrastructure) and
 * long-horizon-agents (moved from Aspirational). Their folder location and
 * URL are unchanged -- this file only controls where they appear in the
 * nav, not where the .md file lives. No doc appears twice.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {type: 'doc', id: 'intro', label: 'Start Here'},

    {
      type: 'category',
      label: 'Foundations',
      link: {type: 'doc', id: 'foundations/index'},
      items: [
        'foundations/what-is-ai',
        'foundations/how-llms-work',
        'foundations/neural-networks',
        'foundations/transformers',
        'foundations/attention',
        'foundations/embeddings',
        'foundations/tokenization',
        'foundations/training-vs-inference',
        'foundations/history-timeline',
        'foundations/history-narrative',
      ],
    },

    {
      type: 'category',
      label: 'Building Blocks',
      link: {type: 'doc', id: 'core-building-blocks/index'},
      items: [
        'core-building-blocks/prompting',
        'core-building-blocks/structured-outputs',
        'core-building-blocks/function-calling',
        'core-building-blocks/rag',
        'core-building-blocks/multi-agent-systems',
        'meta-infrastructure/orchestration-frameworks',
        'core-building-blocks/memory-architectures',
        'aspirational/long-horizon-agents',
      ],
    },

    {type: 'autogenerated', dirName: 'patterns'},
    {type: 'autogenerated', dirName: 'teardowns'},

    {
      type: 'category',
      label: 'Reference: Infrastructure',
      link: {type: 'doc', id: 'meta-infrastructure/index'},
      items: [
        'meta-infrastructure/evals',
        'meta-infrastructure/observability',
        'meta-infrastructure/guardrails',
        'meta-infrastructure/prompt-injection',
        'meta-infrastructure/output-validation',
        'meta-infrastructure/vector-databases',
        'meta-infrastructure/caching',
        'meta-infrastructure/mcp',
        'meta-infrastructure/cost-tracking',
        'meta-infrastructure/latency-optimization',
        'meta-infrastructure/model-routing',
        'meta-infrastructure/model-distillation',
        'meta-infrastructure/synthetic-data',
        'meta-infrastructure/document-processing',
        'meta-infrastructure/knowledge-graphs',
        'meta-infrastructure/red-teaming',
        'meta-infrastructure/audit-logs',
        'meta-infrastructure/access-control',
      ],
    },

    {
      type: 'category',
      label: 'Reference: Production',
      link: {type: 'doc', id: 'production-concerns/index'},
      items: [
        'production-concerns/reliability',
        'production-concerns/graceful-degradation',
        'production-concerns/confidence-estimation',
        'production-concerns/fallbacks',
        'production-concerns/monitoring',
        'production-concerns/deployment-patterns',
      ],
    },

    {
      type: 'category',
      label: 'Reference: Frontier',
      link: {type: 'doc', id: 'aspirational/index'},
      items: [
        'aspirational/agentic-computer-use',
        'aspirational/world-models',
        'aspirational/multimodal-frontier',
        'aspirational/on-device-ai',
        'aspirational/novel-interaction',
        'aspirational/ai-safety',
      ],
    },

    {type: 'doc', id: 'glossary', label: 'Glossary'},
  ],
};

export default sidebars;
